spring:
  datasource:
    url: jdbc:mysql://ea-final-db.crykiiyuw0y2.us-east-1.rds.amazonaws.com:5050/eafinal?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret-key: EAcs544123456789EAcs544123456789EAcs544123456789
  expiration: 180000
server:
  port: 5000